create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text unique,
  category text not null default '',
  cost numeric(14,2) not null default 0 check (cost >= 0),
  price numeric(14,2) not null default 0 check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  min_stock integer not null default 0 check (min_stock >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null,
  cost numeric(14,2) not null default 0 check (cost >= 0),
  price numeric(14,2) not null default 0 check (price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  due numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  due numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('sale','expense','income','payment')),
  amount numeric(14,2) not null check (amount >= 0),
  payment_method text not null default '',
  note text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(id) on delete set null,
  total numeric(14,2) not null check (total >= 0),
  discount numeric(14,2) not null default 0 check (discount >= 0),
  paid numeric(14,2) not null default 0 check (paid >= 0),
  payment_method text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint not null references public.products(id),
  qty integer not null check (qty > 0),
  unit_price numeric(14,2) not null check (unit_price >= 0),
  unit_cost numeric(14,2) not null check (unit_cost >= 0)
);

create table if not exists public.settings (
  key text primary key,
  value text not null
);

insert into public.settings(key,value) values
 ('business_name','Tijarah'),('currency','BDT'),('charge_per_1000','13.95')
on conflict (key) do nothing;

alter table public.products enable row level security;
alter table public.services enable row level security;
alter table public.customers enable row level security;
alter table public.suppliers enable row level security;
alter table public.transactions enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.settings enable row level security;

-- Development policy: authenticated Tijarah users can manage business data.
-- Before production, replace this with tenant/user ownership policies.
create policy if not exists products_auth_all on public.products for all to authenticated using (true) with check (true);
create policy if not exists services_auth_all on public.services for all to authenticated using (true) with check (true);
create policy if not exists customers_auth_all on public.customers for all to authenticated using (true) with check (true);
create policy if not exists suppliers_auth_all on public.suppliers for all to authenticated using (true) with check (true);
create policy if not exists transactions_auth_all on public.transactions for all to authenticated using (true) with check (true);
create policy if not exists sales_auth_all on public.sales for all to authenticated using (true) with check (true);
create policy if not exists sale_items_auth_all on public.sale_items for all to authenticated using (true) with check (true);
create policy if not exists settings_auth_all on public.settings for all to authenticated using (true) with check (true);
